@startuml
'https://plantuml.com/class-diagram

class Moi() {
    - unClassifiable
    # Thanks() : Ksss
}
'True ! ( Weak bonded with Time Unit )
"Moi()" -down-o TimeUnit
' These work too (any combination)
'Moi *-down-* TimeUnit
'Moi -down-+ TimeUnit
'Moi -down-# TimeUnit



abstract class AbstractList {
    # AddSomeMethod() : Void
}
abstract AbstractCollection {
    - addingWhyNotAttribute
    - ItemComponent : item
    + __construct(ItemComponent)
}
interface List {
    - JumpitBool
    + Jump("Ouaf !") : void
    }
interface Collection {
    + publicAttribute
    - privateAttribute
    # protectedAttribue
    Collect()
    }

abstract ItemComponent {
    - theme : Moi
}

' Bottom didn't work... (the rabbit)
AbstractCollection *-Right- ItemComponent

List <-- AbstractList
Collection <|-- AbstractCollection
Collection <- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}
enum TimeUnit {
DAYS
HOURS
MINUTES
}

' nice jump !
TimeUnit <-right- List
@enduml